### ISSUE TITLE
esquisse crashing while starting

### ISSUE THREAD

**Issue by nitin194** [amrrs/drag_drop_ggplot_esquisse#1]
First of all many thanks for creating such an awesome tool.

I was trying my hands on with the esquisse package but it's crashing every time I try to execute it. below is the console output details:

#####################################################
> library(esquisse)
> data = read.csv("iris.csv")
> esquisse::esquisser(data)
Loading required package: shiny

Listening on http://127.0.0.1:6376
Warning: Error in observeEvent: unused argument (ignoreInit = TRUE)
Stack trace (innermost first):
    51: observeEvent
    50: module
    49: withReactiveDomain
    48: callModule
    47: <Anonymous>
    46: do.call
    45: server
     3: shiny::runApp
     2: runGadget
     1: esquisse::esquisser
Error in observeEvent(input$changeData, { : 
  unused argument (ignoreInit = TRUE)
#####################################################

The window opens and crashes with this error message, Please suggest how to resolve this issue?

**Comment by amrrs** [comment]
Hi @nitin194 . Thanks for contacting. I am not the creator of this package, I just wrote an article on it. But I'm happy to look into it.

**Comment by amrrs** [comment]
Can you please try with `data` in the argument? I mean

just this

` esquisse::esquisser()`

**Comment by nitin194** [comment]
Hello Amrrs,

Thanks for your suggestion. The problem did not resolved yet. I also tried to include the argument but no fate. Could you please point me to the creator of this package?

Listening on http://127.0.0.1:4443
Warning: Error in observeEvent: unused argument (ignoreInit = TRUE)
Stack trace (innermost first):
    51: observeEvent
    50: module
    49: withReactiveDomain
    48: callModule
    47: <Anonymous>
    46: do.call
    45: server
     3: shiny::runApp
     2: runGadget
     1: esquisse::esquisser
Error in observeEvent(input$changeData, { : 
  unused argument (ignoreInit = TRUE)

> esquisse::esquisser(data,ignoreInit = TRUE)
Error in esquisse::esquisser(data, ignoreInit = TRUE) : 
  unused argument (ignoreInit = TRUE)

**Comment by amrrs** [comment]
Oh. This is where you can raise similar issue. I'd also encourage you to log your `sessionInfo()` in the new issue!

**Comment by nitin194** [comment]
Sure, please point me to the creator for this package. That would be really helpful

**Comment by amrrs** [comment]
oh sorry i thought i pasted the link that's my bad. https://github.com/dreamRs/esquisse/issues here it is.

**Comment by nitin194** [comment]
Thank you @amrrs
